**머신 러닝 모델을 학습시키고 평가하기 위해서는 데이터를 적절하게 분리하는 작업이 필요하다.**

In [1]:
# 임포트
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# **지도 학습(Supervised Learning)**  
지도 학습의 훈련 데이터는 정답이 무엇인지 맞춰 하는 '문제'에 해당되는 데이터와 레이블이라고 부르는 '정답'이 적혀있는 데이터로 구성되어 있다.

기계는 X_train과 y_train에 대해서 학습을 한다.  
학습을 다한 기계에서 y_test는 보여주지 않고, X_test에 대해서 정답을 예측하게 한다.  
그리고 기계가 예측한 답과 실제 정답인 y_test를 비교하면서 기계가 정답을 얼마나 맞췄는지를 평가한다. 이 수치가 기계의 정확도(Accuracy)가 된다.  
**<훈련 데이터>**  
X_train : 문제지 데이터  
y_train : 문제지에 대한 정답 데이터  
**<테스트 데이터>**  
X_test : 시험지 데이터  
y_test : 시험지에 대한 정답 데이터  

# **X와 y분리하기**

### **1. zip 함수를 이용하여 분리하기**

In [2]:
# zip() 함수
# 동일한 개수를 가지는 시퀀스 자료형에서 각 순서에 등장하는 원소들끼리 묶어주는 역할
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print("X 데이터 :", X)
print("y 데이터 :", y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [3]:
# 리스트의 리스트 또는 행렬 또는 2D 텐서
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
print("X 데이터 :", X)
print("y 데이터 :", y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


### **2. 데이터프레임을 이용하여 분리하기**

In [5]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]

columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [6]:
X = df["메일 본문"]
y = df["스팸 메일 유무"]

print("X 데이터 :", X.to_list())
print("y 데이터 :", y.to_list())

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


### **3.Numpy를 이용하여 분리하기**

In [7]:
# numpy의 슬라이싱을 사용하여 데이터를 분리
np_array = np.arange(0, 16).reshape((4, 4)) # 0부터 15까지 4X4
print("전체 데이터 :")
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [8]:
# 마지막 열을 제외하고 X 데이터에 저장
# 마지막 열은 y 데이터에 저장
X = np_array[:, :3]
y = np_array[:, 3]

print("X 데이터 :")
print(X)
print("y 데이터 :", y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


# **테스트 데이터 분리하기**

### **1. 사이킷 런을 이용하여 분리하기**  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1234)
    # X : 독립 변수 데이터
    # y : 종속 변수 데이터
    # test_size : 테스트용 데이터 개수를 지정. 1보다 작은 실수를 기재할 경우 비율을 나타낸다.
    # train_size : 학습용 데이터의 개수를 지정.
    # random_state : 난수 시드

In [9]:
# 임의로 X와 y 데이터를 생성
X, y = np.arange(10).reshape((5, 2)), range(5)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))

X 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]


In [12]:
# 7:3의 비율로 훈련 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

print('X 훈련 데이터 :')
print(X_train)
print('X 테스트 데이터 :')
print(X_test)

print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

X 훈련 데이터 :
[[2 3]
 [4 5]
 [6 7]]
X 테스트 데이터 :
[[8 9]
 [0 1]]
y 훈련 데이터 :
[1, 2, 3]
y 테스트 데이터 :
[4, 0]


### **수동으로 분리하기**

In [15]:
# 실습을 위해 임의로 X와 y가 이미 분리 된 데이터를 생성
X, y = np.arange(0,24).reshape((12,2)), range(12)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))

X 전체 데이터 :
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
y 전체 데이터 :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [17]:
# 훈련 데이터의 개수
num_of_train = int(len(X) * 0.8) # 데이터의 전체 길이의 80%에 해당하는 길이값을 구한다.
# 테스트 데이터의 개수
num_of_test = int(len(X) - num_of_train) # 전체 길이에서 80%에 해당하는 길이를 뺀다.
print('훈련 데이터의 크기 :',num_of_train)
print('테스트 데이터의 크기 :',num_of_test)

## 여기서 num_of_test를 len(X) * 0.2로 계산해서는 안된다.
## 데이터에 누락이 발생할 수 있다.

훈련 데이터의 크기 : 9
테스트 데이터의 크기 : 3


In [19]:
X_test = X[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
y_test = y[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
X_train = X[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장
y_train = y[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장

print('X 테스트 데이터 :')
print(X_test)
print('y 테스트 데이터 :')
print(list(y_test))

X 테스트 데이터 :
[[18 19]
 [20 21]
 [22 23]]
y 테스트 데이터 :
[9, 10, 11]
