In [1]:
import numpy as np

### **np.array()**  
리스트, 튜플, 배열로부터 ndarray를 생성한다.

In [5]:
# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)

print("vec의 축의 개수 :", vec.ndim) # 축의 개수 출력
print("vec의 크기(shape) :", vec.shape) # 크기 출력

[1 2 3 4 5]
vec의 축의 개수 : 1
vec의 크기(shape) : (5,)


In [7]:
# 2차원 배열
mat = np.array([[10, 20, 30], [60, 70, 80]])
print(mat)

print("mat의 축의 개수 :", mat.ndim) # 축의 개수 출력
print("mat의 크기(shape) :", mat.shape) # 크기 출력

[[10 20 30]
 [60 70 80]]
mat의 축의 개수 : 2
mat의 크기(shape) : (2, 3)


In [8]:
# 타입 확인
print("vec의 타입 :", type(vec))
print("mat의 타입 :", type(mat))

vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>


### **ndarray의 초기화**

In [9]:
# 모든 값이 0인 2X3 배열 생성
zero_mat = np.zeros((2, 3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 모든 값이 1인 2X3 배열 생성
one_mat = np.ones((2, 3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# 모든 값이 특정 상수인 배열 생성
same_value_mat = np.full((2, 2), 2)
print(same_value_mat)

[[2 2]
 [2 2]]


In [12]:
# 대각선 값이 1이고 나머지 값이 0인 2차원 배열 생성
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 임의의 값으로 채워진 배열 생성
random_mat = np.random.random((2, 3))
print(random_mat)

[[0.41596012 0.09671143 0.13508883]
 [0.71383763 0.85103099 0.9212394 ]]


### **np.arange()**  
0부터 (n-1)까지의 값을 가지는 배열을 생성

In [14]:
# 0부터 9까지
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# 1부터 9까지 +2씩 적용되는 범위
n = 2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


### **np.reshape()**  
내부 데이터는 변경하지 않으면서 배열의 구조를 바꾼다.

In [16]:
reshape_mat = np.array(np.arange(30)).reshape((5, 6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### **Numpy 슬라이싱**

In [17]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [18]:
# 첫번째 행 출력
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [19]:
# 두번째 열 출력
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


### **Numpy 정수 인덱싱**

In [21]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [22]:
# 1행 0열의 원소
# 0부터 카운트하므로 두번째 행 첫번째 열의 원소
print(mat[1, 0])

4


In [23]:
# mat[[2행, 1행], [0열, 1열]]
indexing_mat = mat[[2, 1], [0, 1]]
print(indexing_mat)

[7 5]


### **Numpy 연산**

In [24]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [25]:
# result = np.add(x, y)
result = x + y
print(result)

[5 7 9]


In [26]:
# result = np.subtract(x, y)
result = x - y
print(result)

[-3 -3 -3]


In [27]:
# result = np.multiply(result, x)
result = result * x
print(result)

[-3 -6 -9]


In [28]:
# result = np.divide(result, x)
result = result / x
print(result)

[-3. -3. -3.]


In [29]:
# 행렬 곱
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]
